server:
  port: 7502
spring:
  application:
    name: app-kafka
  kafka:
    client-id: app-kafka
    bootstrap-servers: ENC(jrMQvbryXDudpCfqfE5q2wWWQzuCnw72x3vlLBG2SPk=)  # Kafka 服务地址
    consumer:
      auto-offset-reset: earliest       # 从最早的消息开始消费
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
knife4j:
  enable: true
springdoc:
  swagger-ui:
    path: /swagger-ui.html

encryptor:
  key: HRQv9voExyEIo5GI6C62sNe0PvmalQE1D7+dxTGR3fY=
  prefix: ENC(
  suffix: )

thread-pool:
  executors:
    - executor-name: default
      core-size: 10
      max-size: 10
      queue-capacity: 100
      keep-alive-time: 0
      keep-alive-time-unit: MILLISECONDS
      reject-policy: CALLER_RUNS
    - executor-name: file-upload
      core-size: 10
      max-size: 10
      queue-capacity: 100
      keep-alive-time: 0
      keep-alive-time-unit: MILLISECONDS
      reject-policy: CALLER_RUNS